// test binary, proof of concept llm + discord
// vdisc is a Discord utility that fetches chat history from a specified channel,
// discovers accessible channels across guilds, and uses an LLM provider
// to generate a concise summary of the conversation history.

package main

import (
	"context"
	"fmt"
	"log/slog"
	"os"
	"regexp"
	"strings"
	"uaa/vdnd/internal/llm"

	"github.com/bwmarrin/discordgo"
	"github.com/caarlos0/env/v11"
	"github.com/joho/godotenv"
)

type Config struct {
	Token       string `env:"DISCORD_TOKEN"`
	ChannelID   string `env:"DISCORD_CHANNEL_ID"`
	GeminiKey   string `env:"GEMINI_API_KEY"`
	GroqKey     string `env:"GROQ_API_KEY"`
	OllamaURL   string `env:"OLLAMA_URL"`
	LLMProvider string `env:"LLM_PROVIDER" envDefault:"groq"`
	LLMModel    string `env:"LLM_MODEL" envDefault:"qwen/qwen3-32b"`
}

func main() {
	// Open log file
	logFile, err := os.OpenFile("vdisc.log", os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0644)
	if err != nil {
		fmt.Fprintf(os.Stderr, "failed to open log file: %v\n", err)
		os.Exit(1)
	}
	defer logFile.Close()

	// Initialize structured logger
	handler := slog.NewTextHandler(logFile, &slog.HandlerOptions{Level: slog.LevelDebug})
	slog.SetDefault(slog.New(handler))

	_ = godotenv.Load()

	cfg := Config{}
	if err := env.Parse(&cfg); err != nil {
		slog.Error("failed to parse config", "error", err)
		os.Exit(1)
	}

	if cfg.Token == "" || cfg.ChannelID == "" {
		slog.Error("DISCORD_TOKEN and DISCORD_CHANNEL_ID must be set")
		os.Exit(1)
	}

	dg, err := discordgo.New("Bot " + cfg.Token)
	if err != nil {
		slog.Error("error creating Discord session", "error", err)
		os.Exit(1)
	}

	// Initialize LLM Provider
	var p llm.Provider
	switch cfg.LLMProvider {
	case "gemini":
		if cfg.GeminiKey != "" {
			p, err = llm.NewGeminiProvider(context.Background(), cfg.GeminiKey, cfg.LLMModel)
		}
	case "ollama":
		p, err = llm.NewOllamaProvider(cfg.LLMModel, cfg.OllamaURL)
	case "groq":
		if cfg.GroqKey != "" {
			p, err = llm.NewGroqProvider(cfg.GroqKey, cfg.LLMModel)
		}
	}

	if err != nil {
		slog.Error("failed to initialize LLM provider", "error", err)
		os.Exit(1)
	}

	err = dg.Open()
	if err != nil {
		slog.Error("error opening connection", "error", err)
		os.Exit(1)
	}
	defer dg.Close()

	fmt.Println("Connected to Discord.")

	// List all channels the bot has access to
	fmt.Println("Permitted Channels:")
	guilds, err := dg.UserGuilds(100, "", "", false)
	if err != nil {
		fmt.Printf("Error fetching guilds: %v\n", err)
	} else {
		for _, g := range guilds {
			channels, err := dg.GuildChannels(g.ID)
			if err != nil {
				fmt.Printf("  Error fetching channels for guild %s (%s): %v\n", g.Name, g.ID, err)
				continue
			}
			fmt.Printf(" Guild: %s (%s)\n", g.Name, g.ID)
			for _, c := range channels {
				if c.Type == discordgo.ChannelTypeGuildText {
					fmt.Printf("  - #%s (%s)\n", c.Name, c.ID)
				}
			}
		}
	}

	fmt.Printf("\nQuerying history for channel %s...\n", cfg.ChannelID)

	// Query last 100 messages
	messages, err := dg.ChannelMessages(cfg.ChannelID, 100, "", "", "")
	if err != nil {
		slog.Error("error fetching messages", "error", err)
		os.Exit(1)
	}

	fmt.Println("Recent messages:")
	var sb strings.Builder
	for i := len(messages) - 1; i >= 0; i-- {
		m := messages[i]
		line := fmt.Sprintf("[%s] %s: %s\n", m.Timestamp.Format("15:04:05"), m.Author.Username, m.Content)
		fmt.Print(line)
		sb.WriteString(line)
	}

	if p != nil {
		fmt.Println("\nSummarizing chat history...")
		prompt := fmt.Sprintf("Please provide a concise summary, maximum 1800 characters, of the following chat history:\n\n%s", sb.String())
		resp, err := p.GenerateWithTools(context.Background(), []llm.Message{
			{Role: "user", Content: prompt},
		}, nil)
		if err != nil {
			fmt.Printf("Error generating summary: %v\n", err)
		} else {
			headerStdout := fmt.Sprintf("\n--- LLM SUMMARY (%s/%s) ---\n", cfg.LLMProvider, cfg.LLMModel)
			fmt.Printf("%s%s\n-------------------\n", headerStdout, resp.Content)

			// Strip <think> tags before sending to Discord
			cleanContent := stripThinkTags(resp.Content)

			// Send the summary to the Discord channel
			footerDiscord := fmt.Sprintf("\n\n_Generated by %s using %s_", cfg.LLMProvider, cfg.LLMModel)
			_, err = dg.ChannelMessageSend(cfg.ChannelID, fmt.Sprintf("**Chat Summary:**\n%s%s", cleanContent, footerDiscord))
			if err != nil {
				fmt.Printf("Error sending summary to Discord: %v\n", err)
			} else {
				fmt.Println("Summary sent to Discord.")
			}
		}
	}

	fmt.Println("Shutting down...")
}

func stripThinkTags(content string) string {
	// Remove <think>...</think> blocks including the tags themselves
	re := regexp.MustCompile(`(?s)<think>.*?</think>`)
	cleaned := re.ReplaceAllString(content, "")
	return strings.TrimSpace(cleaned)
}
